# Generated by Django 5.0.7 on 2024-07-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(
                default="admin@gmail.com",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(default="admin", max_length=255),
            preserve_default=False,
        ),
    ]
