# Generated by Django 5.0.7 on 2024-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("CLOSE", "Close"),
                ],
                default="Open",
                max_length=12,
            ),
        ),
    ]
