# Generated by Django 5.0.7 on 2024-07-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0002_alter_issue_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("Open", "Open"),
                    ("In Progress", "In Progress"),
                    ("Closed", "Closed"),
                ],
                default="Open",
                max_length=12,
            ),
        ),
    ]
