# Generated by Django 5.0.7 on 2024-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0005_issue_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
