# Generated by Django 5.0.7 on 2024-09-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_issue_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="priority",
            field=models.CharField(
                choices=[("HIGH", "High"), ("MEDIUM", "Medium"), ("LOW", "Low")],
                default="LOW",
                max_length=8,
            ),
            preserve_default=False,
        ),
    ]
