# Generated by Django 5.0.7 on 2024-08-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_is_admin_user_is_staff_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
