# Generated by Django 5.0.7 on 2024-08-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_rename_name_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
